apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-tracker-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-tracker-redis
  template:
    metadata:
      labels:
        app: crypto-tracker-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-tracker-redis
spec:
  selector:
    app: crypto-tracker-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
